config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/tasks', to: 'tasks#index', as: :tasks

  get '/tasks/new', to: 'tasks#new'
  post '/tasks', to: 'tasks#create'

  get '/tasks/:id', to: 'tasks#show', as: :task

  get '/tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch '/tasks/:id', to: 'tasks#update'

  delete '/tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save!

    redirect_to task_path(@task)
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    @task.update(task_params)

    redirect_to task_path(@task)
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy

    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="stylesheet" href="https://site-assets.fontawesome.com/releases/v6.1.1/css/all.css">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<div class="container">
  <h1>Update Task</h1>
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="flexCheckDefault" <% if task.completed %>
      checked
    <% end %>>
    <label class="form-check-label" for="flexCheckDefault">
    <%= link_to task.title, task_path(task) %>

    <%= link_to '<i class="fa-solid fa-trash-can"></i>'.html_safe, task_path(task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
    </label>
  </div>
<% end %>
<hr>
<%= link_to '+ Add a new task', tasks_new_path %>

app/views/tasks/new.html.erb
<div class="container">
  <h1>Create Task</h1>
  <%= simple_form_for(@task) do |f| %>
    <%= f.input :title %>
    <%= f.input :details %>
    <%= f.input :completed %>
    <%= f.submit %>
  <% end %>
</div>

app/views/tasks/show.html.erb
<div class="container" >
  <h1><%= @task.title %></h1>
  <p><%= @task.details %></p>
  <p>Status: <% if @task.completed %>
    Completed
  <% else %>
    Incomplete
  <% end %></p>

  <%= link_to "Update Task", edit_task_path(@task) %>
  <br>
  <%= link_to "< Back", tasks_path %>
  <br>
  <%= link_to "Delete #{@task.title}",
            task_path(@task),
            method: :delete,
            data: { confirm: "Are you sure?" } %>
</div>